// <auto-generated />
namespace Network_Inventory_System_Beta.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class runSeed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(runSeed));
        
        string IMigrationMetadata.Id
        {
            get { return "201704111819129_runSeed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
